SELECT
    CL.CDCLINNOME,
    FU.CDFNOME,
    LC.LCADATAHORAATEND
FROM
    LCATENDIMENTO as LC
    INNER JOIN CDCLIENTE CL ON CL.CDCLICODIGO = LC.LCACLIENTE
    INNER JOIN CDFUNCIONARIO FU ON FU.CDFCODIGO = LC.LCAFUNCIONARIO
ORDER BY
    CL.CDCLINNOME

SELECT
    CL.CDCLINNOME,
    LC.LCADATAHORAATEND
FROM
    LCATENDIMENTO as LC
    INNER JOIN CDCLIENTE CL ON CL.CDCLICODIGO = LC.LCACLIENTE
WHERE
(LC.LCADATAHORAATEND >= '01.01.2011' OR LC.LCADATAHORAATEND <= '01.02.2011') OR
(LC.LCADATAHORAATEND >= '01.07.2011' OR LC.LCADATAHORAATEND <= '31.12.2011')
    





